base/urls.py
from django.urls import path
from . import views
app_name = 'basic_app'
urlpatterns = [
    path('', views.home, name='home'),
    path('add/', views.addToTask, name='addTask'),
    path('edit/<str:pk>/', views.editTask, name='editTask'),
    path('delete/<str:pk>/', views.deleteTask, name='deleteTask'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout')
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

base/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.
class Category(models.Model):    
    id = models.AutoField(primary_key=True)
    user_choices  = [('important', 'Important')]
    user_choice = models.CharField(max_length=15, default=user_choices[0], choices=user_choices)
    def __str__(self):
        return self.user_choices[0][0]
    
class Task(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    task_category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True, related_name='task_categorized')
    
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=1200)
    time = models.DateTimeField(null=True, blank=True)
    completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['-created_at',]
        
    def __str__(self):
        return self.title

    

base/forms.py
from django import forms
from .models import Task, Category
from django.contrib.auth.models import User
# from django.forms import forms
class TaskForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control input', 'placeholder': 'Title'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control input', 'placeholder': 'Your task...'}))
    time = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'class': 'form-group', 'type': 'datetime-local'}))
    completed = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class': 'checkbox px-5', 'type':'checkbox'}), required=False)
    def clean(self):
        all_cleaned_data = super().clean()
        title = all_cleaned_data['title']
        description = all_cleaned_data['description']
        if len(str(title)) < 1:
            return forms.ValidationError('Please ensure that you have typed a title')
        if len(str(description)) < 1:
            return forms.ValidationError('Please ensure that you have typed a title')
    class Meta:
        model = Task
        fields = ('title', 'description', 'time', 'completed')


class LoginForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    
    class Meta:
        model = User
        fields = ('username', 'password')

base/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect, JsonResponse, HttpResponseNotFound, HttpResponseForbidden
from base.forms import TaskForm
from base.models import Task, Category
from django.urls import reverse
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate
import json

# from validate_email import validate_email
from django.core.validators import validate_email
# Create your views here
@login_required(login_url='basic_app:login')
def home(request):
    if request.method == 'GET':
        query = request.GET.get('query') if request.GET.get('query') != None else ''
        tasks = Task.objects.filter(user=request.user).order_by('time')
    return render(request, 'base/home.html', {'tasks': tasks})
@login_required(login_url='basic_app:login')
def editTask(request, pk):
    task = Task.objects.get(id=pk, user=request.user)
    form = TaskForm(instance=task)
    if request.user == task.user:
        if request.method == 'POST':
            form = TaskForm(request.POST, instance=task)
            if form.is_valid():
                form.save(commit=False)
                task.save()
                return HttpResponseRedirect(reverse('basic_app:home'))
    else:
        return HttpResponseNotFound('Not found !!')    
    return render(request, 'base/edittask.html', {'form': form})
@login_required(login_url='basic_app:login')
def deleteTask(request, pk):
    task = Task.objects.get(id=pk, user=request.user)
    if request.user == task.user:
        if request.method == 'POST':
            task.delete()
            return redirect('/')
    else:
        return HttpResponseNotFound('Not found !!')
    

@login_required(login_url='basic_app:login')
def addToTask(request):
    form = TaskForm
    if request.method == 'POST':
        form = TaskForm(data=request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.user = request.user
            task.save()
            return HttpResponseRedirect(reverse('basic_app:home'))
    return render(request, 'base/taskAdd.html', {'form': form})
def validate_useremail(request):
    if request.method == 'POST':
        data = json.loads(request.POST)
        email = email
        if not validate_email(email):
            return JsonResponse({'error': 'Invalid email'})
        if User.objects.filter(email=email).exists():
            return JsonResponse({'error': 'A user with this email already exists'}, status=400)
        else:
            return JsonResponse({'status': True})
def validate_username(request):
    if request.method == 'POST':
        data = json.loads(request)
        username = data['username']
    if not username.isalnum():
        return JsonResponse({'error': 'Ensure your username is alphanumeric'}, status=400)  

    if User.objects.filter(username=username).exists():
        return JsonResponse({'error': 'A uesr with this username already exist'}, status=400)  
    else:
        return JsonResponse({'status': True})  
def validate_password(request):
    if request.method == 'POST':
        data = json.loads(request)
        password = data['password']  
        if len(str(password)) < 7:
            return  JsonResponse({'error': 'Minimum length of password is 7 due to security reasons'}, status=400)
        else:
            return JsonResponse({'status': True})
def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        confirmPassword = request.POST.get('confirmPassword')
        if not validate_email(email):
            return redirect('basic_app:login')
        
        if password != confirmPassword:
            print('user-eq error')
            
            return redirect('basic_app:login')
        if len(str(password).strip()) < 7:
            print('pass-strip error')
            
            return redirect('basic_app:login')
        if User.objects.filter(username=username) == False:
            print('user-us error')
            return redirect('basic_app:login')
        if User.objects.filter(email=email).exists():
            print('user-ex error')
            return redirect('basic_app:login')
        if len(str(username).strip()) < 1:
            print('username-str error')
            
            return reverse('basic_app:login')
        if not username.isalnum():
            print('user-aln error')
            return reverse('basic_app:login')
        else:
            user = User.objects.create_user(username=username, email=email)
            user.save()
            user.set_password(confirmPassword)
            user.save()
            return HttpResponseRedirect(reverse('basic_app:login'))
    return render(request, 'base/register.html')

def user_login(request):
    if request.method  == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('basic_app:home'))
    return render(request, 'base/signin.html')


def user_logout(request):
    logout(request)
    return redirect('/')

def addCategory(request, task_pk):
    task = get_object_or_404(Task, id=task_pk)
    if request.method == 'post':
        choice = request.POST.get('choice')
        category = Category.objects.create()
        category.choices.append()
    

base/templates/base/display.html
{% extends 'base/nav.html' %}
{% block todoTitle %} <title>Register</title> {% endblock %}
{% block body_block %}


{% endblock %}

base/templates/base/edittask.html
{% extends 'base/nav.html' %}
{% block todoTitle %} <title>Edit Task</title> {% endblock %}

{% block body_block %}
<div class="container-fluid">
    <div class="wrap-content">
        <form method="post" class="form-group">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary">Add to task</button>
        </form>
    </div>
</div>
{% endblock %}

base/templates/base/home.html
{% extends 'base/nav.html' %}
{% block todoTitle %} <title>Home Page</title> {% endblock %}
{% block body_block %}
<style>
    html{
        position: relative;
        width: 100%;
    }
    .material-symbols-outlined{
        font-size: 1rem;
    }
    .alert{

    }
    a{
        color: #000;
    }
    table{
        width: 100%;
    }
    #myAlert{
        position: absolute;
    width: 100%;
    max-width: 40%;
    left: 31%;
    top: 40%;
    display: none;
    z-index: 2;
    }
    #myAlert.active{
        display: block;
    }
</style>
<div  class='container-fluid'>
<div class="">
    <div class="wrap-content-container mt-3">
        <div class="">
            <div class="add-btn d-flex">
                <button class="btn btn-secondary d-flex align-items-center ms-auto my-2">
                    <a style="text-decoration: none; color: #000;" href="{% url 'basic_app:addTask' %}">
                        <span class="material-symbols-outlined">
                            add
                            </span>
                            Add to task    
                    </a></button>
            </div>
            <div class="filter-btn mb-2">
                <div class="dropdown">
                    <button class="btn btn-outline-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-label="false">
                        <span class="material-symbols-outlined">
                            filter_list
                            </span>
                        Filter
                    </button>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="" class="dropdown-item">Important</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="table table-responsive">
                <table class="table">
                    <thead class="bg-light">
                        <tr>
                            <th>
                                Title
                            </th>
                            <th style="cursor: pointer;" class="dropdown dropdown-toggle" data-bs-toggle="dropdown" aria-label="false">
                                Deadline
                                <span class="caret"></span>
                                <ul class="dropdown-menu">
                                <li class="dropdown-item">Today</li>
                                <li class="divider"></li>
                                <li class="dropdown-item">Add to date</li>
                                </ul>
                            </th>
                            <th>Day's left</th>
                            <th>Content</th>
                            <th>Edit</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for task in tasks %}
                        <tr>
                            <td>
                                {{task.title}}
                               </div>
                            </td>
                            <td class="timer">{% if task.time == None %}No deadline given{% else %} {{task.time|date}} {% endif %}</td>
                            <td class="text-danger days-left">
                                <div class="spinner-border"></div>
                            </td>
                            <td>{{task.description|truncatewords:11|linebreaks}}</td>
                            <td><button class="btn btn-outline-primary">
                                <a class="d-flex align-items-center" style="text-decoration: none; color: #000;" href="{% url 'basic_app:editTask' task.id %}">
                                    <span class="material-symbols-outlined">
                                        edit
                                    </span>
                                    Edit
                                </a>
                                </button></td>
                            <td><button class="btn delete-task d-flex align-items-center btn-danger"><span class="material-symbols-outlined">delete</span>
                                Delete</button></td>

                        </tr>

                        <div id="myAlert" class="alert shadow alert-warning">
                            <a href="#" class="close close-text-alert mb-1 text-decoration-none d-flex align-items-center" data-dismiss="alert">
                               <span  style="font-size: 1.5rem;" class="material-symbols-outlined">
                                   cancel
                                   </span>
                            </a>
                            <strong>Warning!</strong> 
                            <form action="{% url 'basic_app:deleteTask' task.id %}" method="post">
                                {% csrf_token %}
                               <span>Are you sure you want to delete</span>
                               <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                           
                           </div>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% block javascriptCode %} <script type="text/javascript">
const timer = document.querySelectorAll('.timer')
const daysLeft = document.querySelectorAll('.days-left')
    function counter(datePlaced){

    const datePlacedVal = new Date(datePlaced)
    const datePlacedMillisecs = datePlacedVal.getTime()
    
    const presentDate = new Date()
    const presentDateMillisecs = presentDate.getTime()
    const milliIntevral = datePlacedMillisecs - presentDateMillisecs
    const IntervalSeconds = milliIntevral / 1000
    
    const days = Math.floor(IntervalSeconds / 3600 / 24)
    const hours = Math.floor(IntervalSeconds / 3600) % 24
    const mins = Math.floor(IntervalSeconds / 60) % 60
    const seconds = Math.floor(IntervalSeconds) % 60
    if(datePlacedVal == presentDate || datePlacedVal < presentDate){
        return 'Time up'
    }
    else{
        return `${days} days, ${hours}hrs:${mins}mins:${seconds} sec left` 
    }
}
timer.forEach((element, index)=>{
    const val = element.innerHTML
    setInterval(function(){
        console.log(val)
        if(val != 'No deadline given'){
            const daysLeftVal = counter(val)
        if(daysLeftVal === 'Time up'){
            daysLeft[index].innerHTML = 'Completed'
            daysLeft[index].classList.remove('text-danger')
            daysLeft[index].classList.add('text-success')

        }
        daysLeft[index].innerHTML = daysLeftVal     
        }else{
        daysLeft[index].innerHTML = 'No deadline given'     

        }

    }, 1000)
})
const deleteBtn = document.querySelectorAll('#myAlert')
const deleteTaskBtn = document.querySelectorAll('.delete-task')
const cancelDeleteBtn = document.querySelectorAll('.close-text-alert')
let currentBtn = 'closed'
deleteTaskBtn.forEach((element, index)=>{
    element.addEventListener('click', ()=>{
        
    deleteBtn[index].classList.add('active')
    console.log(index)
})

})
cancelDeleteBtn.forEach((element, index)=>{
    element.addEventListener('click', ()=>{
    deleteBtn[index].classList.remove('active')

    })
})
</script> {% endblock %}

{% endblock %}

base/templates/base/nav.html
{% load static %}
<style>
    html{
        box-sizing: border-box;
        font-size: 100%;
        width: 100%;
    }
</style>
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block todoTitle %} <title></title> {% endblock %}
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- Google roboto fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

<!-- Google icons -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />

<link rel="stylesheet" href="{% static 'css/home.css' %}">
{% block stylesheetA %} <link rel="stylesheet" href=""> {% endblock %}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">
</head>
  <body>
    <div  class="container-fluid py-0 px-0 my-0 mx-0">
        <div class="wrap-nav">
            <nav class="navbar-expand-lg justify-content-center bg-light navbar-light navbar" role="navigation">
                <div class="container-fluid navbar justify-content-between">
                    <a class="navbar-brand mb-0 h1">Todo App</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainNav">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse justify-content-between navbar-collapse" id="mainNav">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a href="" class="nav-link active">Home</a>
                            </li>
                            {% if user.is_authenticated %}
                            <li class="nav-item dropdown">
                                <a href="" class="dropdown-toggle nav-link" role="button" data-bs-toggle="dropdown" aria-expanded="false">Categories</a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="" class="dropdown-item">
                                            Add to later
                                        </a>
                                    </li>
                                    <li><a href="" class="dropdown-item">
                                        Add to important
                                    </a></li>
                                    <li><hr class="dropdown-divider"></li>

                                    <li><a href="" class="dropdown-item">Add a category</a></li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a href="/logout/" class="nav-link">Logout</a>
                            </li>
                            {% else %}
                            <li class="nav-item">
                                <a href="/register/" class="nav-link">Register</a>
                            </li>
                            <li class="nav-item">
                                <a href="/login/" class="nav-link">
                                    Login</a>
                            </li>
                            {% endif %}
                        </ul>
                        <div class="d-flex mr-auto">
                            <form class="form-inline d-flex" role="search">
                                <input placeholder="Search..." name="query" type="search" aria-label="search" class="search me-2 form-control">
                                <button class="btn-primary btn me-3" type="submit">
                                    Search
                                </button>
                            </form>
                            <div class="d-flex align-items-center">
                                <span style="font-size: 1.5rem;" class="material-symbols-outlined">
                                    account_circle
                                    </span>
                                {% if user.is_authenticated %}
                                @{{user.username}}
                                {% else %}
                                @user
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
        <div class="content-wrap container-fluid">
            {% block body_block %}

            {% endblock %}
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="{% static 'js/home.js' %}"></script>
    {% block javascriptCode %} {{block.super}} <script></script> {% endblock %}
    
  </body>
</html>

base/templates/base/register.html
{% extends 'base/nav.html' %}
{% block todoTitle %} <title>Register</title> {% endblock %}
{% block body_block %}
<div class="container-fluid">
    <header>
        <h2 class="h2">Sign up</h2>
    </header>
    <div class="wrap-content">
        <form method="post" class="form form-group">
            {% csrf_token %}
            <p>
                <label for="username">Username:</label>
                <input type="text" placeholder="Username" name="username" id="" class="form-control">
            </p>
            <p>
                <label for="email">Email</label>
                <input placeholder="Email" class="form-control email" type="email" name="email" id="">
            </p>
            <p>
                <label for="password">Password</label>
                <input type="password" class="form-control" name="password" id="" placeholder="Password">
            </p>
            <p>
                <label for="confirmPassword">Confirm Password</label>
                <input type="password" class="form-control" name="confirmPassword" placeholder="Confirm Password" id="">
            </p>
            <p>
                Do you have an account?
                <a href="/login/">Sign in</a>
            </p>
            <button type="submit" class="btn btn-outline-primary">Sign up</button>
        </form>
    </div>
</div>
{% endblock %}

base/templates/base/signin.html
{% extends 'base/nav.html' %}
{% block todoTitle %} <title>Register</title> {% endblock %}
{% block body_block %}
<div class="container-fluid">
    <header>
        <h2 class="h2">Sign up</h2>
    </header>
    <div class="wrap-content">
        <form method="post" class="form form-group">
            {% csrf_token %}
            <p>
                <label for="username">Username:</label>
                <input type="text" placeholder="Username" name="username" id="" class="form-control">
            </p>
            <p>
                <label for="password">Password</label>
                <input type="password" class="form-control form-input" name="password" id="" placeholder="Password">
            </p>
            <p>
                Do you have an account?
                <a href="/register/">Sign in</a>
            </p>
            <button type="submit" class="btn btn-outline-primary">Sign up</button>
        </form>
    </div>
</div>
{% endblock %}

base/templates/base/taskAdd.html
{% extends 'base/nav.html' %}
{% block todoTitle %} <title>Add to Task</title> {% endblock %}

{% block body_block %}
<div class="container-fluid">
    <div class="wra-content">
        <div class="form-container">
            <form action="" method="post" class="form">
                {% csrf_token %}
                {{form.as_p}}
            
                <button type="submit" class="btn btn-primary">Add to task</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}